/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const TestIndexLazyImport = createFileRoute('/test/')()
const ProjectsNetflixIndexLazyImport = createFileRoute('/projects/netflix/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TestIndexLazyRoute = TestIndexLazyImport.update({
  path: '/test/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/test/index.lazy').then((d) => d.Route))

const ProjectsNetflixIndexLazyRoute = ProjectsNetflixIndexLazyImport.update({
  path: '/projects/netflix/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/projects/netflix/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/test/': {
      preLoaderRoute: typeof TestIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects/netflix/': {
      preLoaderRoute: typeof ProjectsNetflixIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  TestIndexLazyRoute,
  ProjectsNetflixIndexLazyRoute,
])

/* prettier-ignore-end */
